"""Initial schema v0.5.0 to v0.6.0

Revision ID: 45490ea63a06
Revises: 
Create Date: 2025-11-22 06:59:56.950704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45490ea63a06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique token ID'))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable token name'))
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=False, comment='JSON string of permissions'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Whether token is active (can be disabled)'))
        batch_op.alter_column('token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_index('idx_api_tokens_revoked')
        batch_op.create_index('idx_active_tokens', ['is_active', 'token'], unique=False)
        batch_op.create_index('idx_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_token', ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_token'), ['token'], unique=True)
        batch_op.drop_column('revoked')
        batch_op.drop_column('description')

    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('last_updated',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('max_users_timestamp')
        batch_op.drop_column('max_connected_timestamp')
        batch_op.drop_column('max_connected')

    with op.batch_alter_table('current_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='offline', nullable=False, comment='Bot status (online/offline/connecting)'))
        batch_op.add_column(sa.Column('current_users', sa.Integer(), server_default='0', nullable=False, comment='Current chat-enabled users'))
        batch_op.add_column(sa.Column('connected_users', sa.Integer(), server_default='0', nullable=False, comment='Current total connected users'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bot_afk')
        batch_op.drop_column('bot_name')
        batch_op.drop_column('bot_rank')
        batch_op.drop_column('current_media_duration')
        batch_op.drop_column('bot_start_time')
        batch_op.drop_column('playlist_items')
        batch_op.drop_column('current_chat_users')
        batch_op.drop_column('bot_connected')
        batch_op.drop_column('channel_name')
        batch_op.drop_column('current_media_title')
        batch_op.drop_column('current_connected_users')

    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if send failed'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('sent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('idx_outbound_sent')
        batch_op.create_index('idx_sent', ['sent'], unique=False)
        batch_op.create_index('idx_sent_timestamp', ['sent', 'timestamp'], unique=False)
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_sent'), ['sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('last_error')
        batch_op.drop_column('sent_timestamp')

    with op.batch_alter_table('recent_chat', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index('idx_recent_chat_timestamp')
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_chat_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_username', ['username'], unique=False)
        batch_op.create_index('idx_username_timestamp', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_actions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_actions_username'), ['username'], unique=False)

    with op.batch_alter_table('user_count_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index('idx_user_count_timestamp')
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_count_history_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('total_chat_lines',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_time_connected',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index('idx_last_seen', ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stats_last_seen'), ['last_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stats_last_seen'))
        batch_op.drop_index('idx_last_seen')
        batch_op.alter_column('total_time_connected',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_chat_lines',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_count_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_count_history_timestamp'))
        batch_op.drop_index('idx_timestamp')
        batch_op.create_index('idx_user_count_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_actions_username'))
        batch_op.drop_index(batch_op.f('ix_user_actions_timestamp'))
        batch_op.drop_index('idx_username_timestamp')
        batch_op.drop_index('idx_username')
        batch_op.drop_index('idx_timestamp')
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('recent_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_chat_timestamp'))
        batch_op.drop_index('idx_timestamp')
        batch_op.create_index('idx_recent_chat_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_timestamp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_sent'))
        batch_op.drop_index('idx_timestamp')
        batch_op.drop_index('idx_sent_timestamp')
        batch_op.drop_index('idx_sent')
        batch_op.create_index('idx_outbound_sent', ['sent', 'timestamp'], unique=False)
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('error_message')

    with op.batch_alter_table('current_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_connected_users', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('current_media_title', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('channel_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bot_connected', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('current_chat_users', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('playlist_items', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('bot_start_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_media_duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bot_rank', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('bot_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bot_afk', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.alter_column('last_updated',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('connected_users')
        batch_op.drop_column('current_users')
        batch_op.drop_column('status')

    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_connected', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('max_connected_timestamp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('max_users_timestamp', sa.INTEGER(), nullable=True))
        batch_op.alter_column('last_updated',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('revoked', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_is_active'))
        batch_op.drop_index('idx_token')
        batch_op.drop_index('idx_is_active')
        batch_op.drop_index('idx_active_tokens')
        batch_op.create_index('idx_api_tokens_revoked', ['revoked', 'token'], unique=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('permissions')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
